// @ts-nocheck
import { browser } from '@hanzo/docs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("@hanzo/docs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"api.mdx": () => import("../content/docs/api.mdx?collection=docs"), "architecture.mdx": () => import("../content/docs/architecture.mdx?collection=docs"), "benchmarks.mdx": () => import("../content/docs/benchmarks.mdx?collection=docs"), "consensus.mdx": () => import("../content/docs/consensus.mdx?collection=docs"), "ecosystem.mdx": () => import("../content/docs/ecosystem.mdx?collection=docs"), "gateway.mdx": () => import("../content/docs/gateway.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "post-quantum.mdx": () => import("../content/docs/post-quantum.mdx?collection=docs"), "protocol.mdx": () => import("../content/docs/protocol.mdx?collection=docs"), "quick-start.mdx": () => import("../content/docs/quick-start.mdx?collection=docs"), "transports.mdx": () => import("../content/docs/transports.mdx?collection=docs"), "why-zap.mdx": () => import("../content/docs/why-zap.mdx?collection=docs"), "sdks/c.mdx": () => import("../content/docs/sdks/c.mdx?collection=docs"), "sdks/cpp.mdx": () => import("../content/docs/sdks/cpp.mdx?collection=docs"), "sdks/csharp.mdx": () => import("../content/docs/sdks/csharp.mdx?collection=docs"), "sdks/erlang.mdx": () => import("../content/docs/sdks/erlang.mdx?collection=docs"), "sdks/go.mdx": () => import("../content/docs/sdks/go.mdx?collection=docs"), "sdks/haskell.mdx": () => import("../content/docs/sdks/haskell.mdx?collection=docs"), "sdks/index.mdx": () => import("../content/docs/sdks/index.mdx?collection=docs"), "sdks/java.mdx": () => import("../content/docs/sdks/java.mdx?collection=docs"), "sdks/ocaml.mdx": () => import("../content/docs/sdks/ocaml.mdx?collection=docs"), "sdks/python.mdx": () => import("../content/docs/sdks/python.mdx?collection=docs"), "sdks/rust.mdx": () => import("../content/docs/sdks/rust.mdx?collection=docs"), "sdks/typescript.mdx": () => import("../content/docs/sdks/typescript.mdx?collection=docs"), "protocols/a2a.mdx": () => import("../content/docs/protocols/a2a.mdx?collection=docs"), "protocols/acp.mdx": () => import("../content/docs/protocols/acp.mdx?collection=docs"), "protocols/fix.mdx": () => import("../content/docs/protocols/fix.mdx?collection=docs"), "protocols/http.mdx": () => import("../content/docs/protocols/http.mdx?collection=docs"), "protocols/index.mdx": () => import("../content/docs/protocols/index.mdx?collection=docs"), "protocols/mcp.mdx": () => import("../content/docs/protocols/mcp.mdx?collection=docs"), "protocols/native.mdx": () => import("../content/docs/protocols/native.mdx?collection=docs"), "protocols/rns.mdx": () => import("../content/docs/protocols/rns.mdx?collection=docs"), "protocols/ws.mdx": () => import("../content/docs/protocols/ws.mdx?collection=docs"), }),
};
export default browserCollections;